-- 1. What is the total amount each customer spent at the restaurant?

SNOWFLAKE Query:
WITH CTE AS (
SELECT S.CUSTOMER_ID,
       S.PRODUCT_ID,
       COUNT(*) AS CNT,
       M.PRICE
FROM DANNYS_DINER.PUBLIC.SALES S
INNER JOIN MENU M
ON S.PRODUCT_ID = M.PRODUCT_ID
GROUP BY ALL
)

MYSQL Solution:
SELECT CUSTOMER_ID,
       SUM(CNT * PRICE) AS AMOUNT_SPENT
FROM CTE
GROUP BY ALL;

WITH CTE AS (
SELECT S.CUSTOMER_ID,
       S.PRODUCT_ID,
       COUNT(*) AS CNT,
       M.PRICE
FROM DANNYS_DINER.PUBLIC.SALES S
INNER JOIN MENU M
ON S.PRODUCT_ID = M.PRODUCT_ID
GROUP BY 1,
         2,
         4
)

SELECT CUSTOMER_ID,
       SUM(CNT * PRICE) AS AMOUNT_SPENT
FROM CTE
GROUP BY 1;
