-- 2. How many days has each customer visited the restaurant?

SNOWFLAKE Query:

SELECT CUSTOMER_ID,
       COUNT(DISTINCT ORDER_DATE) AS NO_OF_VISITS
FROM DANNYS_DINER.PUBLIC.SALES
GROUP BY ALL;

MYSQL Query:
SELECT CUSTOMER_ID,
       COUNT(DISTINCT ORDER_DATE) AS NO_OF_VISITS
FROM DANNYS_DINER.PUBLIC.SALES
GROUP BY 1;
